db/pgsql/patroni/.pipeline/test/e2e.js, db/pgsql/patroni/openshift/mals-db-deploy-dev.param, db/pgsql/patroni/openshift/mals-db-deploy-prod.param, db/pgsql/patroni/openshift/mals-db-deploy-test.param, db/pgsql/patroni/openshift/mals-db-deploy-uat.param, db/pgsql/patroni/openshift/templates/deployment.yaml, db/pgsql/patroni/test/deploy.sh
Updated the deployment.yaml file to default to patroni:v13-latest to reflect the recent database upgrade.
=> Updated the deployment file to use patroni:v13-latest

db/pgsql/db-scripts/create-fs-10/create_mals_objects.bat, db/pgsql/db-scripts/create-fs-10/sql/create_mals_01_tables.sql, db/pgsql/db-scripts/create-fs-10/sql/create_mals_02_views.sql, db/pgsql/db-scripts/create-fs-10/sql/create_mals_03_foreign_keys.sql, db/pgsql/db-scripts/create-fs-10/sql/create_mals_04_grants.sql, db/pgsql/db-scripts/create-fs-10/sql/create_mals_05_trigger_function.sql, db/pgsql/db-scripts/create-fs-10/sql/create_mals_06_before_triggers.sql, db/pgsql/db-scripts/create-fs-10/sql/create_mals_07_lookup_dml.sql
=> Data model updates per FS-10. Added mal_site, updated others.

db/pgsql/db-scripts/create-fs-13/create_mals_objects.bat, db/pgsql/db-scripts/create-fs-13/sql/create_mals_01_tables.sql, db/pgsql/db-scripts/create-fs-13/sql/create_mals_02_lookup_dml.sql, db/pgsql/db-scripts/create-fs-13/sql/create_mals_03_views.sql, db/pgsql/db-scripts/create-fs-13/sql/create_mals_04_foreign_keys.sql, db/pgsql/db-scripts/create-fs-13/sql/create_mals_05_plpgsql.sql, db/pgsql/db-scripts/create-fs-13/sql/create_mals_06_before_triggers.sql, db/pgsql/db-scripts/create-fs-13/sql/create_mals_07_grants.sql, db/pgsql/patroni/openshift/sample_deploy/deploy_dev.bat, db/pgsql/patroni/openshift/sample_deploy/deploy_test.bat, db/pgsql/patroni/openshift/sample_deploy/deploy_uat.bat
Added FS-13 database scripts and Talend jobs.
=> Added FS-13 database scripts and Talend jobs.

spilo-db/db-scripts/create-db/sql/spilo_01_db_and_users.sql, spilo-db/db-scripts/create-db/sql/spilo_02_dblink.sql
=> Updated create db scripts

spilo-db/README.md, spilo-db/db-scripts/rel05.3/release-ddl.sql
=> Updates to database objects per Jira tasks.

app/server/routes/v1/documents.js, openshift/app.dc.yaml
=> Point CDOGS to api gateway

spilo-db/db-scripts/rel05.3/release-ddl.sql
=> Updated mal_print_card_vw per MALS-1184

app/client/src/features/sites/dairytanks/DairyTankDetailsEdit.jsx, app/client/src/features/sites/dairytanks/DairyTanksEdit.jsx, app/client/src/features/sites/dairytanks/DairyTanksViewEdit.jsx
=> Resolve dairy tanks generating additional/unwanted data

app/client/src/features/licences/LicenceDetailsViewEdit.jsx, app/server/keycloak.js
=> Display correct licence number in renewal modal

app/client/src/features/licences/ViewLicencePage.jsx, app/client/src/features/search/LicenceResultsPage.jsx, app/client/src/features/search/SiteResultsPage.jsx, app/client/src/features/sites/ViewSitePage.jsx, app/client/src/react-app-env.d.ts
=> Resolve old data carry over

app/client/src/features/documents/SelectApiaryRenewalsPage.jsx, app/client/src/features/documents/SelectDairyNoticesPage.jsx, app/client/src/features/documents/SelectDairyTankNoticesPage.jsx, app/client/src/features/documents/SelectRenewalsPage.jsx, app/prisma/schema.prisma, app/prisma/views.prisma
=> Default docgen checkboxes to checked

app/client/src/features/licences/LicenceDetailsViewEdit.jsx
=> Read licence renewal dates from admin config

app/client/src/features/documents/SelectApiaryRenewalsPage.jsx, app/client/src/features/documents/SelectCertificatesPage.jsx, app/client/src/features/documents/SelectDairyNoticesPage.jsx, app/client/src/features/documents/SelectDairyTankNoticesPage.jsx, app/client/src/features/documents/SelectRenewalsPage.jsx
=> Resolve issue with generate button disabled on page entry

app/client/src/features/licences/LicenceDetailsViewEdit.jsx
=> Resolve timestamp issue with licence expiry date

spilo-db/db-scripts/rel05.3/release-ddl.sql
=> Updates per Jira tickets

app/client/src/features/licences/LicenceDairyTestInventory.jsx, app/server/routes/v1/licences.js
=> Resolve licence dairy inventory crash

app/server/models/premisesDetail.js
This should fix the toUpperCase error
=> fix for touppercase undefined error

spilo-db/db-scripts/releases/release_5.2_ddl.sql
=> Release 5.2 updates

app/client/src/features/licences/AssociatedLicences.jsx
MALS-1243 & MALS-1244
Conditionally render certain tables for associated licences to add more information.
=> MALS-1243 & MALS-1244

app/client/src/utilities/api.ts
Added some log statements to help troubleshoot the issues with the test environment
=> debugging with logs

app/client/src/utilities/api.ts, app/server/middleware/roleValidation.js
Removing the debug logging and updated an error check
=> remove debug logs, update user error check

app/client/package-lock.json, app/client/package.json, app/package-lock.json, app/package.json
Update the version number from 5.2.0 to 5.3.0
=> 5.2.0->5.3.0

app/client/src/features/licences/LicenceDetailsViewEdit.jsx
Auto check the print license checkbox when renew license is clicked
=> Auto Check Print License on License Renew

app/client/src/features/licences/LicenceDetailsViewEdit.jsx
=> Auto check Print Licence on Renew Licence

app/client/src/features/licences/LicenceDetailsViewEdit.jsx
=> Auto check print licence on renewal

Dockerfile
=> adjust node version

app/client/public/index.html
=> feat: Restart app via code change

app/client/public/index.html
=> fix: Update index.html

spilo-db/db-scripts/releases/release_5.4_ddl.sql
- MScallion's database updates for MALS-26
=> MALS-26 db changes

app/client/src/features/licences/GenerateDairyTrailerInspection.jsx, app/client/src/features/licences/LicenceTrailers.jsx, spilo-db/db-scripts/releases/release_5.4_ddl.sql
- trailer inspection report procedure fix
- small qol update for generate button
=> 5.4 db release update

app/server/routes/v1/documents.js
- Report name for Licence Comments report is now licence_number-report_type.xlsx
- Same report name for dairy trailer inspection report
=> update document name when generated

app/client/src/features/inspections/ApiaryInspectionDetailsEdit.jsx, app/client/src/features/inspections/CreateInspectionPage.jsx, app/client/src/features/inspections/InspectionDetailsViewEdit.jsx, app/client/src/features/reports/ReportLicenceComments.jsx, app/client/src/features/trailerinspections/CreateTrailerInspectionPage.jsx, app/client/src/features/trailerinspections/TrailerInspectionDetailsEdit.jsx, app/server/routes/v1/documents.js, app/server/routes/v1/inspections.js, spilo-db/db-scripts/releases/release_5.5_ddl.sql
- Licence Comments report now checks for an irma_number match and if it can't find one, it looks for a licence_number match
- Remove debug logging
=> MALS2-17 - overload licence comment report for irma

spilo-db/db-scripts/releases/release_5.5_ddl.sql
=> MALS2-17 - fix licence comments overload logic

spilo-db/db-scripts/releases/release_5.5_ddl.sql
Database changes for 5.5
- MALS2-17 - licence comments report view and procedure
=> WIP - Create release_5.5_ddl.sql

spilo-db/db-scripts/releases/release_5.5_ddl.sql
- Small fix to MALS2-24 statement
=> add missing db reference

spilo-db/db-scripts/releases/release_5.6_ddl.sql
- Add missing view and grants to the 5.6 database script
=> 5.6 db script update

app/client/src/features/lookups/Cities.jsx, app/client/src/features/sites/SiteDetailsEdit.jsx
- Site Edit page City dropdown was not displaying anything despite storing the correct value.
=> fix city dropdown issue

app/client/src/features/lookups/Cities.jsx, app/client/src/features/sites/SiteDetailsEdit.jsx, app/client/src/modals/AddressModal.jsx
reverting these changes in test to better troubleshoot the issue
=> Revert fixes in test

app/client/package-lock.json, app/client/package.json, app/package-lock.json, app/package.json
- Update version number
- Deploying Keycloak changes to prod
- Deploying tickets MALS2-42, 43, 44
=> update version number 5.6.1 -> 5.7.0

spilo-db/db-scripts/releases/release_5.8_ddl.sql
---
Thanks for the PR!
Deployments, as required, will be available below:
- [Frontend](https://nr-mals-538-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-mals-538-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-mals/actions/workflows/analysis.yml)
After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-mals/actions/workflows/merge.yml)
=> feat: MALS2-45 - Dairy Client Details Report including Inactive sites

frontend/package-lock.json, frontend/package.json
---
Thanks for the PR!
Deployments, as required, will be available below:
- [Frontend](https://nr-mals-543-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-mals-543-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-mals/actions/workflows/analysis.yml)
After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-mals/actions/workflows/merge.yml)
=> feat: MALS2-64 part 2 - axios version 0.21.0 -> 1.12.2

backend/package-lock.json, backend/package.json
---
Thanks for the PR!
Deployments, as required, will be available below:
- [Frontend](https://nr-mals-544-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-mals-544-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-mals/actions/workflows/analysis.yml)
After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-mals/actions/workflows/merge.yml)
=> feat: MALS2-64 part 3 - backend axios 0.21.0 -> 1.12.2
